apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-job-runner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-job-runner
  template:
    metadata:
      labels:
        app: kubernetes-job-runner
    spec:
      serviceAccountName: job-runner-sa
      containers:
      - name: kubernetes-job-runner
        image: your-docker-repo/kubernetes-job-runner:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: KUBERNETES_SERVICE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP